config/routes.rb
Trek::Application.routes.draw do
  get "tickets/index"

  get "tickets/show"

  get "purchase/index"

  get "purchase/show"

  get "purchase/create"

  get "purchase/destroy"

  get "groups/show"

  get "groups/new"

  get "groups/index"

  get "medias/create"

  get "medias/destroy"

  get "medias/update"

  get "digest_emails/create"

  get "watched_plans/create"

  get "watched_plans/destroy"

  get "admin/index"

  get "dislikes/create"

  get "dislikes/destroy"

  get "likes/create"

  get "likes/destroy"

  get "comments/create"

  get "comments/destroy"

  get "authentications/index"

  get "authentications/create"

  get "authentications/destroy"

  get "blocks/create"
  get "blocks/destroy"

  get "subscribed_challenges/create"
  get "subscribed_challenges/destroy"


  match '/auth/:provider/callback' =>'authentications#create'


  devise_for :users, :as => '', :path_names => { :sign_in => "login", :password => "reset_password" }, :controllers => { :sessions => 'sessions' } do
    get "/logout" => "devise/sessions#destroy"
    match "/api/login", :to => "sessions#create", :via => [:get, :post], :mobile => true
    
    get '/auth/:provider' => 'sessions#passthru'
    
    match '/auth/twitter/setup', :to => 'sessions#twitter_setup'
    match '/auth/facebook/setup', :to => 'sessions#fb_setup'

  end

  resources :users
  match 'confirm_email/:id' => 'users#confirm_email', :as => :confirm_email

  resources :medias
  resources :challenges
  resources :admin
  resources :groups
  resources :tickets
  resources :adventures, :controller => "challenges"
  
  
  
  
  match 'export_guest' => 'admin#export_guest', :as => :export_guest
  match 'display_users' => 'admin#display_users', :as => :display_users
  
  match 'get_subscribed' => 'subscribed_plans#get_subscribed', :as => :get_subscribed
  
  match 'refresh_challenges' => 'challenges#refresh_challenges', :as => :refresh_challenges
  match 'geocoder' => 'challenges#geocoder', :as => :geocoder
  match 'geocode_plan' => 'plans#geocode_plan', :as => :geocode_plan
  
  
  
  match 'download_ics' => 'plans#download_ics', :as => :download_ics
  
  match 'ajax_redraw_planning_box' => 'challenges#ajax_redraw_planning_box', :as => :ajax_redraw_planning_box
  
  resources :subscribed_challenges
  match 'bucket_list' => 'subscribed_challenges#bucket_list', :as => :bucket_list
  match 'panda_callback' => 'subscribed_challenges#panda_callback', :as => :panda_callback
  match 'regenerate_embed' => 'subscribed_challenges#regenerate_embed', :as => :regenerate_embed
  match 'add_note' => 'subscribed_challenges#add_note', :as => :add_note
 
  resources :messages
  match 'inbox' => 'messages#inbox', :as => :inbox
  match 'sent' => 'messages#sent', :as => :sent
  match 'notifications' => 'messages#notifications', :as => :notifications
  match 'reply_message' => 'messages#reply_message', :as => :reply_message
  match 'no_cc' => 'messages#no_cc', :as => :no_cc
  
  resources :achievements
  resources :blocks
  resources :comments
  resources :likes
  resources :dislikes
  match '/plans/featured.:format', :controller => 'plans', :action => 'featured'
  
   match '/escapes/:id/purchase', :controller => 'purchase', :action => 'show'
  
  resources :purchase
  resources :plans
  resources :escapes, :controller => "plans"
  match '/edit_plan_date', :controller => 'plans', :action => 'edit_plan_date'
  
  match 'my_escapes' => 'plans#my_escapes', :as => :my_escapes
  
  match "plans/:id", :controller => 'plans', :action => 'show', :via => [:get, :post]
  resources :digest_emails
  resources :subscribed_plans
  resources :watched_plans
  match 'initial_comment' => 'comments#initial_comment', :as => :initial_comment
  
  
  match 'spotlight' => 'web#spotlight', :as => :spotlight
  
  
  match 'check_group_username' => 'groups#check_group_username', :as => :check_group_username
  
  match 'spotlight2' => 'web#spotlight2', :as => :spotlight2
  match 'new_home' => 'web#new_home', :as => :new_home
  match 'live_search' => 'web#live_search', :as => :live_search
  match 'search' => 'web#search', :as => :search
  match 'refresh_spotlight' => 'web#refresh_spotlight', :as => :refresh_spotlight
  match 'rewards' => 'web#rewards', :as => :leaders
  match 'about' => 'web#about', :as => :about
  match 'jobs' => 'web#jobs', :as => :jobs
  match 'tos' => 'web#tos', :as => :tos
  match 'privacy_policy' => 'web#privacy_policy', :as => :privacy_policy
  match 'settings' => 'web#settings', :as => :settings
  match 'weeklyemail' => 'web#weeklyemail', :as => :weeklyemail
  
  match 'request' => 'city_requests#create', :via => :post
  match 'register' => 'users#register', :as => :register
  match 'my_challenges' => 'users#my_challenges', :as => :my_challenges
  match 'profile' => 'users#profile'
  match 'next_challenge', :controller => "web", :action=>"next_challenge"
  match 'refresh_container', :controller => "web", :action=>"refresh_container"
  match 'new_refresh_container', :controller => "web", :action=>"new_refresh_container"

  match 'create_search_results', :controller => "challenges", :action=>"create_search_results"
  match 'achievement_live_results', :controller => "achievements", :action=>"achievement_live_results"
  
  match 'confirmation', :controller => 'plans', :action => 'confirmation'
  match 'wepay_callback', :controller => 'plans', :action => 'wepay_callback'
   match 'paypal_ipn', :controller => 'plans', :action => 'paypal_ipn'
  match 'discover', :controller => 'plans', :action => 'discover'
  match 'check_plan_password', :controller => 'plans', :action => 'check_plan_password'
  
  match 'new_plan', :controller => 'plans', :action => 'new_plan' 
  match 'payment', :controller => 'subscribed_plans', :action => 'payment' 
  
  match 'create', :controller => 'web', :action => 'apply'
  match 'host_an_adventure', :controller => 'web', :action => 'host_an_adventure'
 
  match 'test', :controller => 'web', :action => 'test'
  match 'upgrade_browser', :controller => 'web', :action => 'upgrade_browser'
  match ':username', :controller => 'users', :action => 'show'
  
  
  
  # API - Users
  # match 'api/login', :controller => 'users', :action => 'mobile_login', :via => [:get, :post]
  match 'api/register', :controller => 'users', :action => 'mobile_create', :via => [:get, :post]
  match 'api/users/:id.:format', :controller => 'users', :action => 'show'
  match 'api/scan_addressbook.:format', :controller => 'users', :action => 'scan_addressbook'
  match 'api/invite.:format', :controller => 'users', :action => 'invite'
  match 'api/mobile_livesearch.:format', :controller => 'challenges', :action => 'mobile_livesearch'
  
  root :to => "web#new_home"
end

app/controllers/plans_controller.rb
#require 'we_pay'
 
class PlansController < ApplicationController
  
  #include ActiveMerchant::Billing::Integrations
  
  
  include GeoKit::Geocoders
  before_filter :login_from_token, :only => [:featured]
  
  def featured
    
  end
  
  

  
  
  def paypal_ipn
    
    if request.post?
       notify = Paypal::Notification.new(request.raw_post)
       if notify.acknowledge
           if notify.complete?
             
             @user_id = params[:custom].to_i
             @plan_id = params[:item_number].to_i
             @qty = params[:quantity].to_i
             @amountpaid = params[:mc_gross]
             @email = params[:payer_email]

             #ugly temp hack. to be replaced by callback. Need to figre out QTY.
             check = SubscribedPlan.find_by_plan_id_and_user_id(@plan_id,@user_id)
             unless check
               SubscribedPlan.create(:plan_id => @plan_id, :user_id=>@user_id, :num_guests=>@qty)
               @user =  User.find(@user_id)
               @plan = Plan.find(@plan_id)

               if @plan.price and @plan.price > 0
                 if @user.discount_active == true
                   @user.discount_active = false
                   @user.save
                 end 
               end
               
               if @plan.group
                 if @plan.group.mailchimp_key and @plan.group.mailchimp_list
                   if @plan.group.mailchimp_key != "" and @plan.group.mailchimp_list != "" 
                     begin
                       h = Hominid::API.new(@plan.group.mailchimp_key)
                       h.list_subscribe(@plan.group.mailchimp_list, @user.email, {'FNAME' => @user.first_name, 'LNAME' => @user.last_name}, 'html', false, true, true, false)
                    rescue
                      
                    end
                  end
                 end
               end

               Postoffice.deliver_confirmation(@user,@plan)
              end
           end
       end
       render :nothing => true
     end
  end
  
  
  
  def wepay_callback
    
    #if event == "Received Money"
      
    #  o = OAuth::Consumer.new( WePay::CONSUMER_KEY, WePay::SHARED_SECRET, {
    #            :site => WePay::APIURL,
    #            :http_method => :post,
    #            :authorize_path => "/v1/oauth/authorize",
    #            :access_token_path => "/v1/oauth/access_token",
    #            :request_token_path => "/v1/oauth/request_token"})

        # Get a request token 
    #    request_token = o.get_request_token({
    #            :oauth_callback => "http://stomp.io/wepay_callback",
    #            :scheme => :query_string })

    #    access_token = request_token.get_access_token({:oauth_verifier => verifier})
        
    #    transacation = wp.get("/group/transactions/589165")
        
      
    #end
    
  end
  
  
  
  def create
    
    if current_user
      
      if params[:plan][:application_deadline] and params[:plan][:application_deadline] != ""
       date_and_time = '%m/%d/%Y'
       params[:plan][:application_deadline] = DateTime.strptime("#{params[:plan][:application_deadline]}", date_and_time)
      end 
      
      if params[:plan][:url_link] != ""
        params[:plan][:url_link] = "http://#{params[:plan][:url_link]}"
      end
       
      @plan = Plan.new(params[:plan])
    
      if params[:plan_price_radio].to_i == 1
        @plan.price = 0
      end
    
      @plan.featured = 1
      @plan.privacy = 1
    
      #if @group
      #  @plan.group_id = @group.id
      #end
      
      if @plan.group_id == 0
         @plan.group_id = nil
      end
     
      @plan.city_id = 99
      @plan.short_location = params[:plan][:url_name]
      
      if params[:plan][:url_name] == "Place, business, or landmark"
        @plan.url_name = nil
      end
    
      @plan.enable_comments = 1
      @plan.enable_sharing = 1
      @plan.enable_signups = 1
      
      if params[:plan][:enable_discount] == "on"
        @plan.enable_discount = true
      end
      

      
      if params[:application] == "2"
        @plan.application_required = true
      end
    

    
       combine_times
     
    
       if @plan.location != "Type anything Google Maps can figure out"
         loc = MultiGeocoder.geocode(@plan.location)
         if loc.success
           calc_closest_city(loc)
           @plan.city_id = @returned_city_id
           @plan.lat = loc.lat
           @plan.lng = loc.lng
         end

       end
       
    
    
    
  
       @plan.save!
      
       update_tickets
         
          @plan.save!
      
      
      Host.create(:user_id => current_user.id, :plan_id => @plan.id, :admin=>true)
      
    
      redirect_to "/escapes/#{@plan.id}"
      
    end
    
    
  end
  
  
  def destroy
    
    

      @plan = Plan.find(params[:id])
      
      if current_user
        
        if current_user.mod_level == 5
          @plan.destroy
        else
        
          for host in @plan.organizers
            if host.id == current_user.id
              @plan.destroy
            end
          end
        end
      end
      
      render :nothing => true
      
      
  end
  
  
  def show
    
    @plan = Plan.find(:first, :conditions=>["id=?",params[:id]])
 
     if !@plan
        redirect_to "/"
        return
      end
      
      @tickets = @plan.tickets.sort_by_type
      
      
    @photos = Media.find(:all, :conditions=>["plan_id=? and media_type = ?",@plan.id,0], :order=>"sort_order asc")
    
   
    
    
    if @plan.location
      @cleaned_location = @plan.location.gsub(%r{</?[^>]+?>}, ' ').gsub(/%3Cbr%3E/,' ').gsub(/%20/,' ').gsub(/<br>/,' ').gsub(/&nbsp;/,' ').gsub(/%26nbsp;/, ' ')
    end
    
    
    @watched = false
    if current_user
      if current_user.has_watched?(@plan)
        @watched = true
      end
    end
    
    
    @real_edit_for_toggle = false
    
    
    #all hosts have access
    plan_access_control
    
    
    if cookies[:disable_edit]
      @editable = false
    end
    
    
    #redirect if password protected?
    if @plan.privacy == 3
      
      if cookies[:password] and (cookies[:password].downcase == @plan.password.downcase)
        redirect = false
      else
        redirect = true
      end
    else
      redirect = false
    end
    
    if @admin
      redirect = false
    end
    if @editable
      redirect = false
    end
    if redirect
      redirect_to "/?id=#{@plan.id}"
      return
    end
    
  if current_user
    @subscribed = @plan.has_signedup?(current_user)
  end
  if current_user && @subscribed
    @signedup = TRUE
    @signup_color = "Red"
  else
    @signedup = FALSE
    @signup_color = "Green"
  end



  
  





  end
  
  
  def download_ics
    
    
    @plan = Plan.find(params[:id])
    
    ical = RiCal.Calendar do |cal|
          cal.event do |event|
            event.description = "#{@plan.strip_short_desc}\n#{@plan.grab_url}"
            if @plan.start_time
              event.dtstart =  @plan.start_time.utc + 5.hours
            end
            if @plan.end_time
              event.dtend = @plan.end_time.utc + 5.hours
            end
            event.location = @plan.strip_location
            event.summary = @plan.strip_title
          end
        end
        send_data(ical.export, :filename=>"mycal.ics", :disposition=>"inline; filename=mycal.ics", :type=>"text/calendar")
        
  end
  
 
  def update_tickets
    
    

    
    
    
    
    
    if params[:tickets]
        
        Ticket.update_all("soft_delete = 1", "plan_id=#{@plan.id}")
      
         parsed_json = ActiveSupport::JSON.decode(params[:tickets])
         num = 0
         max = 0
         min = 0
          for ticket in parsed_json["tickets"]
                if ticket["title"]  and ticket["title"] != ""
                  
                  if num == 0
                    min = ticket["amount"].to_i
                  end
                  
                  if ticket["ticket_type"].to_i == 1
                    if ticket["amount"].to_i < min
                      min = ticket["amount"].to_i 
                    end
                    if ticket["amount"].to_i > max
                      max = ticket["amount"].to_i 
                    end
                  end
                  
                  if ticket["ticket_id"].to_i == 0
                    @ticket = Ticket.create(:plan_id => @plan.id, :title=>ticket["title"], :subtitle=>ticket["subtitle"], :amount=>ticket["amount"], :qty=>ticket["qty"], :sort_order=>ticket["sort_order"], :ticket_type=>ticket["ticket_type"], :soft_delete=>false)
                  else
                    @ticket = Ticket.find(ticket["ticket_id"].to_i)
                    @ticket.title = ticket["title"]
                    @ticket.subtitle = ticket["subtitle"]
                    @ticket.amount = ticket["amount"]
                    @ticket.qty = ticket["qty"]
                    @ticket.sort_order = ticket["sort_order"]
                    @ticket.ticket_type = ticket["ticket_type"]
                    @ticket.soft_delete = false
                  end

                  @ticket.save
                  num = num + 1
                end
          end
          
               @plan.price = (min.to_f / 100).to_f

               @plan.price_max = (max.to_f / 100).to_f
               
       end
       
  
    end
  
  def update
    
  

    @plan = Plan.find(params[:id])
    
    
    params[:plan].each  do |key, value| 
      unless key == "image"
        params[:plan][key] = CGI::unescape(value)
        params[:plan][key] = remove_end_breaks(params[:plan][key])
        
        if key == "application_deadline"
          if params[:plan][key] != ""
           date_and_time = '%m/%d/%Y'
           if  params[:plan][key] and  params[:plan][key] != "undefined"
             params[:plan][key] = DateTime.strptime("#{params[:plan][key]}", date_and_time)
            end
          end
        end

        
      end 
    end
    

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_circle_date_small.html.erb
<div class="DateCircle_Small <%if @editable%>EditBoxHide<%else%>addtocal<%end%>" <%if @editable%>onclick="displayEditDate()<%end%>" style=" float:left; margin-left:5px; margin-top:3px;" >

<%if @plan.start_time%>
	<%if @plan.start_time < Time.now + 1.year%>
		<%= @plan.start_time.to_date.strftime('%b').upcase()%><br>
		<%= @plan.start_time.to_date.strftime('%e').strip()%>
	<%else%>

		<div style="font-size:18px; line-height:20px; margin-top:8px;">
			<%= @plan.start_time.to_date.strftime('%Y').strip()%>
		</div>
	<%end%>
<%end%>
</div>
	<%if @editable and @extra_visibility%>
<div style="position:absolute;  margin-left:310px; margin-top:17px">

	<div style="position:absolute; " id="ShowEdit"  onclick="displayEditDate();">
		<img  class="EditIcon" src="/images/ok_pen1.png"   >
	</div>


		
</div>
	<%end%>
	
	<div class="addtocal" class="" style="position:absolute; margin-left:310px; margin-top:40px; width:32px; margin-right:10px">
		<img id="calIcon" src="/images/addcal.png" style="width:20px; height:20px; opacity:.7">
	</div>
	
<div class="DarkBlueLabel <%if @editable%>EditBoxHide<%else%>addtocal<%end%>" style="font-size:18px; float:left; width:240px; margin-top:17px; margin-left:10px;" <%if @editable%>onclick="displayEditDate()<%end%>">
	<%if @plan.start_time%>
		<%@timestring = calc_end_plan_time(@plan.start_time,@plan.end_time)%>
		<div style="line-height:18px;"><%=raw @timestring%></div>
	<%end%>

</div>


<div style="clear:both"></div>

app/views/plans/_gallery.html.erb
<div id="gallery" class="ad-gallery" style="margin-bottom:10px; height:325px">
  <div class="ad-image-wrapper"></div>
  <div class="ad-controls" style="display:none"></div>
  <div class="ad-nav">
    <div class="ad-thumbs">
      <ul class="ad-thumb-list">
	
		<%for photo in photos%>
     	<li>
         <a href="<%=photo.photo.url(:thumb_600)%>">
			<%= image_tag photo.photo.url(:thumb_100), :style=>"", :alt=>"", :title=>"#{photo.caption}", :class=>"Transparent" %>
         </a>
       </li>
		
		<%end%>
		         
      </ul>
    </div>
  </div>
</div>




<script type="text/javascript" src="/javascripts/jquery.ad-gallery.js"></script>

<script type="text/javascript">
  $(function() {
    var galleries = $('.ad-gallery').adGallery({
	width: <%=@picwidth%>,
	height: <%=@picheight%>,
	thumb_opacity: 0.9
	}	
	);
   });
</script>

<div style="clear:both"></div>

app/views/plans/_payment_modal.html.erb
<div id="PaymentModal"> 
	<div class="closeRegister" style="margin-left:535px" onclick="closeRegister()"></div>
	
	<div style="margin-top:3px; margin-left:3px;width:95%; margin-left:auto; margin-right:auto; padding:5px;   text-align:center;">
			<div class="HighlightedTitle"  style="font-size:22px; margin-top:2px;">Purchase Tickets</div>
	</div>
	
	
	<div style="margin-top:15px; width:515px; margin-left:auto; margin-right:auto">
		<input type="hidden" id="redirect" value="0">
		<%=render :partial=>"purchase/ticketbox"%>
	</div>
	
	
</div>

<script>
$(document).ready(function() {

	$('#plan_donation_suggested_amount2').numeric({allow:"."});
 });
</script>

app/views/plans/_wepayjs.html.erb
<form id="BB_BuyButtonForm" style="display:none" action="https://checkout.google.com/api/checkout/v2/checkoutForm/Merchant/830265948339379" id="BB_BuyButtonForm" method="post" name="BB_BuyButtonForm" target="_top">
    <input name="item_name_1" type="hidden" value="<%=strip_tags raw @plan.title%>"/>
<%if @plan.start_time%>
    <input name="item_description_1" type="hidden" value="<%=plan.start_time.strftime('%A, %B %e at %l:%M%p')%>"/>
<%end%>
    <input name="email-allowed" type="hidden" value="false"/>
<input id="item_quantity_1"  name="item_quantity_1" type="hidden" value="1"/>
	<%if current_user%>
		<input name="merchant-private-data" type="hidden" value="<%=current_user.id%>"/>
	<%end%>
    <input id="item_price_1" name="item_price_1" type="hidden" value="5.95"/>
    <input name="item_currency_1" type="hidden" value="USD"/>
    <input name="_charset_" type="hidden" value="utf-8"/>
    <input alt="" src="https://checkout.google.com/buttons/buy.gif?merchant_id=830265948339379&amp;w=117&amp;h=48&amp;style=white&amp;variant=text&amp;loc=en_US" type="image"/>
</form>


<%if @plan.group%><%if @plan.group.paypal_email%><%@paypal_email = @plan.group.paypal_email%><%end%><%end%>
<form id="PaypalForm" style="display:none" action="https://www.paypal.com/cgi-bin/webscr" method="post">
	<input type="hidden" name="cmd" value="_xclick">
	<input type="hidden" name="business" value="<%=@paypal_email%>">
	<input type="hidden" name="lc" value="US">
	<%if @plan.start_time%>
	<input type="hidden" name="item_name" value="<%= strip_tags raw @plan.title%> on <%=plan.start_time.strftime('%A, %B %e at %l:%M%p')%>">
	<%else%>
		<input type="hidden" name="item_name" value="<%= strip_tags raw @plan.title%>">
	<%end%>
	<%if current_user%>
		<input type="hidden" name="custom" value="<%=current_user.id%>">
	<%end%>
	<input type="hidden" id="amount" name="amount" value="<%=@plan.price%>">
	<input type="hidden" name="item_number" value="<%=@plan.id%>">
	<input type="hidden" name="return" value="http://<%=@source%>/escapes/<%=@plan.id%>?confirm=yes" />
	<input type="hidden" name="currency_code" value="USD">
	<input type="hidden" name="button_subtype" value="services">
	<input type="hidden" id="quantity" name="quantity" value="1" />
	<input type="hidden" name="no_note" value="1" />
	<input type="hidden" name="no_shipping" value="1" />
	<input type="hidden" name="tax_rate" value="0">
	<input type="hidden" name="notify_url" value="http://<%=APP_URL%>/paypal_ipn">
	<input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynowCC_LG.gif:NonHosted">
	<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
	<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>


<SCRIPT>
plan_id=<%=plan.id%>
quantity=1;
original_price = <%=plan.price%>;
price=<%=plan.price%>;





function payBill(discount) {
 	
	txt = $("#Payment").html();

	txt2 = '<p class="HighlightedTitle" style="text-align:center">One Moment Please</p><div style="padding-top:5px" align="center"><img src="/images/ajax-loader-bar.gif"</div>'
	
	    var temp = {
	        state0: {
	            html: txt,
	            buttons: { Cancel: false, Checkout: true },
				persistent:false,
	            focus: 1,
				submit: function(v, m, f) {
			         if (v == 0) {
						$.cookie('showAttendPop', null, { path: '/escapes/'});
						$.prompt.close();
							return false;
					} else {
						
						if (price <1) {
							$.cookie('showAttendPop', null, { path: '/escapes/'});
							signUpFree(plan_id)
							
						} else {
							$.cookie('showAttendPop', null, { path: '/escapes/'});
							createBill();
						}
		  				$.prompt.goToState('state1');
						
						return false;
					}
	            }
	        },
	        state1: {
	            html: txt2,
	            buttons: { Close: 0 },
	            focus: 0,
	            submit: function(v, m, f) {
	                if (v === 0) {
						$.cookie('showAttendPop', null, { path: '/escapes/'});
	                    $.prompt.close();
		return false;
	                }
	            }
	        }
	    };
	    $.prompt(temp,{ callback: mycallbackfunc });
}

function mycallbackfunc(v,m,f){
		$.cookie('showAttendPop', null, { path: '/escapes/'});
}


function createBill() {
	
	$("#amount").val(original_price)
	$("#quantity").val(qty)
	$("#PaypalForm").submit();
	
//	$("#item_quantity_1").val(qty)
//	$("#item_price_1").val(original_price)
	
	
	
//	$("#BB_BuyButtonForm").submit();
	

}


$(document).ready(function() {
	$('.tl').tooltip();
	$('.resize').autoResize({
	    // On resize:
	    onResize : function() {
	        $(this).css({opacity:0.8});
	    },
	    // After resize:
	    animateCallback : function() {
	        $(this).css({opacity:1});
	    },
	    // Quite slow animation:
	    animateDuration : 300,
	    // More extra space:
	    extraSpace : 1
	});
	
});	
	$('#transportation').focus(function(){ 
		
		if ($(this).html() == "input directions") {
		window.setTimeout(function() {
	        var sel, range;
	        if (window.getSelection && document.createRange) {
	            range = document.createRange();
	            range.selectNodeContents(document.getElementById("transportation"));
	            sel = window.getSelection();
	            sel.removeAllRanges();
	            sel.addRange(range);
	        } else if (document.body.createTextRange) {
	            range = document.body.createTextRange();
	            range.moveToElementText(document.getElementById("transportation"));
	            range.select();
	        }
	    }, 1);
		}
	});
	
	
	function clearTrans() {
		$('#MeetingPlace').hide(); $('#AddMeeting').show();
		
		$.ajax({
	        type: "POST",
	        url: "<%= plan_path(plan) %>",
	        data: "_method=PUT&plan[transportation]=",
	        success: function(msg){
				animateFlashMessage();
	        }
	     });
	}


	<%if cookies[:confirmSignUp] == 'true'%>
		 $(document).ready(function() {
			

			setTimeout("openSignedUp();",200);
			$.cookie('confirmSignUp', null, { path: '/escapes/'});
		 });
	<%end%>
	

	<%if cookies[:showAttendPop] == 'true'%>
		 $(document).ready(function() {
		 	$.cookie('showAttendPop', null, { path: '/escapes/'});
			<%if @plan.application_required%>
				
			<%end%>
			
			
		
			
		  	setTimeout('$("#attend").click();',1000);
		
		 });
	<%end%>
	
	///Auto signed up with 1 domain with record of one, so check
	<%if @signedup%>
		<%@recent = SubscribedPlan.find(:first, :conditions => ["plan_id = #{@plan.id} and user_id = #{current_user.id} and created_at > ?", 30.seconds.ago])%>
		<%if @recent%>	
		$(document).ready(function() {
			openSignedUp();
			});
		<%end%>
	<%end%>

	<%if cookies[:watchPlan] == 'true'%>
		 $(document).ready(function() {
			setTimeout('watchMouseDown($("#WatchButton"))',100);
		  	setTimeout('$("#WatchButton").click();',100);
			$.cookie('watchPlan', null, { path: '/escapes/'});
		 });
	<%end%>
	
	
</SCRIPT>

app/views/plans/confirmation.html.erb
<div class="HighlightedTitle">Thank for you signing up!</div>